config/routes.rb
Rails.application.routes.draw do
  root 'job#index'
  post 'create' => 'job#create', :as => :create
  get '/export/:id' => 'job#export', :as => :export_job
  get '/delete/:id' => 'job#delete', :as => :delete
  get '/stop/:id' => 'job#stop', :as => :stop

end

app/models/job.rb
class Job < ActiveRecord::Base

  mount_uploader :csv_input, JobCsvUploader
  
  validates :job_name, :presence => true
  validates :csv_input, :presence => true

  enum :status => [ :pending, :processing, :completed, :terminated]

  def background_process(retries = 0)
    if self.csv_input.present?
      begin
        self.update_attributes(:status => :processing)

        ActiveRecord::Base.transaction do
          if retries >= 1
            options = {:headers => false, :encoding => 'UTF-8:UTF-8', :skip_blanks => true }
          else
            options = {:headers => false, :encoding => 'ISO-8859-1:UTF-8', :skip_blanks => true }
          end
          #options = { :headers => true, :encoding => 'iso-8859-1:utf-8', :skip_blanks => true }
          csv_text = File.read(self.csv_input.path.to_s, options)
          csv_text = csv_text.gsub /\n/, ''
          header = true
          #      output_csv = []

      

          CSV.parse(csv_text, options) do |row|
            CSV.open(Rails.root.join("public/reports/", "#{self.id}-report.csv"), "a+") do |output_csv|
              if header
                output_csv << row
                header = false
                next
              end
              next if row[0].blank? or row[0].strip.blank?
              if self.keyword_column.to_i > 0
                strip_row = row[self.keyword_column.to_i]
              else
                strip_row = row[0]
              end
              strip_row.split(',').map(&:strip).each do |keyword|
                next if keyword.blank? or keyword.strip.blank?
                tmp_array = row.dup.map { |item| item.strip.squish if item.present? }
                if self.keyword_column.to_i > 0
                  tmp_array[self.keyword_column.to_i] = keyword
                else
                  tmp_array[0] = keyword
                end
                output_csv << tmp_array
              end
            end
          end
          self.update_attributes(:status => :completed)
        end
      rescue Exception => e
        if retries >= 1
          # self.errors_while_uploading_file(@processed_rows)
          Rails.logger.debug e
          Rails.logger.debug "here it is failed"
          self.update_attributes(:status => :terminated)
          # ExceptionNotifier.notify_exception(e)
        else
          self.background_process(1)
        end

      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/job_controller.rb
require 'csv'
class JobController < ApplicationController

  def index
    @new_job = Job.new
    @jobs = Job.all.order("updated_at DESC")
  end

  def create
    @new_job = Job.new(job_params)
    options = {}
    options1 = {}
    if @new_job.save
      job = @new_job.delay.background_process
      @new_job.update_attributes(:status => :pending, :delayed_job_id => job.id)
      @newo_job = Job.new
      options = { :flash => { :success => "Job saved!" } }
      options1 = { :active_tab => 0 }
    else
      options = { :flash => { :error => @new_job.errors.full_messages.join("<br/>") } }
      options1 = { :active_tab => 1 }
    end
    redirect_to root_path(options1), options
  end

  def job_params
    params.require(:job).permit(:job_name, :csv_input, :keyword_column)
  end
  
  def export
    job = Job.find_by_id(params[:id])
    if job.present?
      send_file "#{Rails.root}/public/reports/#{job.id}-report.csv", :type=> 'text/csv'
    end
  end
  def delete
    @job = Job.find_by_id(params[:id])
    running_job = Delayed::Job.find_by_id(@job.delayed_job_id)
    if running_job.present?
      running_job.destroy
    end
    @job.destroy
    redirect_to root_path, :flash => { :success => "Job is deleted!" } and return
  end

  def stop
    @job = Job.find_by_id(params[:id])
    running_job = Delayed::Job.find_by_id(@job.delayed_job_id)

    if running_job.blank?
      @job.update_attributes(:status => :terminated )
      running_job.destroy if running_job.present?
      redirect_to root_path, :flash => { :error => "Job is not running but terminated!" } and return
    end
    running_job.destroy if running_job.present?
    @job.update_attributes(:status => :terminated )
    redirect_to root_path, :flash => { :success => "Job stopped!" } and return
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def bootstrap_class_for flash_type
    { :success => "alert-success", :error  => "alert-danger", :alert  => "alert-warning", :notice  => "alert-info" }[flash_type.to_sym] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message.html_safe, :class  => "alert #{bootstrap_class_for(msg_type)} alert-dismissible", :role  => 'alert') do
          concat(content_tag(:button, :class  => 'close', :data  => { :dismiss  => 'alert' }) do
              concat content_tag(:span, '&times;'.html_safe, 'aria-hidden' => true)
              concat content_tag(:span, 'Close', :class  => 'sr-only')
            end)
          concat message.html_safe
        end)
    end
    nil
  end

  def active_tab(tab)
    current_tab = if params[:active_tab].present? and params[:active_tab].to_i > 0
      params[:active_tab].to_i
    else
      0
    end
    if tab == current_tab
      return 'in active'
    end
    return ''
  end

end

app/helpers/job_helper.rb
module JobHelper
end

app/views/job/_completed.html.erb
<% if @jobs.blank? %>
  <b>There are no Completed/Terminated Jobs</b>
<% end %>
<table class="table table-responsive table-hover">
  <thead>
    <tr>
      <th>Job ID</th>
      <th>Job Name</th>
      <th>Status</th>
      <th>Date Completed</th>
      <th>Misc Functions</th>
    </tr>
  </thead>
  <tbody>
    <% @jobs.each do |job| %>
      <tr id="job_<%= job.id %>">
        <td><%= job.id %></td>
        <td><%= job.job_name %></td>
        <td><%= job.status.blank? ? 'Pending' : job.status %></td>
        <td><%= job.updated_at.in_time_zone('Eastern Time (US & Canada)').strftime('%B-%d-%Y %H:%M') %></td>
        <td>
          <% if [:pending, :processing, :completed,:terminated].include?(job.status.to_sym) %>
            <div class="dropdown">
              <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                Actions
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                <% if [:completed].include?(job.status.to_sym) %>
                  <li>
                    <%= link_to 'Download Report', export_job_path(job),:target => '_self' %>
                  </li>
                <% end %>
                <% if [:pending, :processing].include?(job.status.to_sym) %>
                  <li>
                    <%= link_to 'Stop Job', stop_path(job)%>
                  </li>
                <% end %>
                <li>
                  <%= link_to 'Delete Job', delete_path(job), :data => { :confirm => "Are you sure you want to delete the job?" } %>
                </li>
              </ul>
            </div>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>


</table>

app/views/job/_form.html.erb
<div class="col-md-1"></div>

<div class="col-md-10" id ="new_job_form">  
  <div class="errors"></div>
  <%= form_for @new_job ,:url => create_path, :html => { :class => "" } do |f| %>
    <div class="form-group">
      <%= f.label :job_name, "Enter a Job Name:" %>
      <%= f.text_field :job_name, :class => 'form-control', :placeholder => "Job Name" %>
    </div>
    <div class="form-group">
      <%= f.label :csv_input, "Select A CSV File to import keywords from!!" %>
      <div class="input-group">
        <span class="input-group-addon upload_right_border"><span class="fa fa-upload"></span></span>
        <%= f.file_field :csv_input, :class => 'upload_left_border btn btn-default btn-file', :accept => "text/csv" %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :keyword_column, "Please give column position of keyword pharse. By default keyword pharase will be on first ( 0 ) position" %>
      <div class="input-group">
        <span class="input-group-addon upload_right_border"><span class="fa fa-columns"></span></span>
        <%= f.number_field :keyword_column %>
      </div>
    </div>

    <button onclick="$(this).html('<i class=\'fa fa-spinner fa-spin\'></i> Processing...');return true;" class="btn btn-primary">Submit</button>
  <% end %>
</div>
<div class="col-md-1"></div>

app/views/job/index.html.erb
<div class="panel with-nav-tabs panel-default">
  <div class="panel-heading">
    <ul class="nav nav-tabs">
      <li role="presentation" class="<%= active_tab(0) %>"><a data-toggle="tab" href="#completed">Completed Jobs and Terminated Jobs</a></li>
      <li role="presentation" class="<%= active_tab(1) %>"><a data-toggle="tab" href="#new_job">New Job</a></li>
    </ul>
  </div>
  <div class="panel-body">
    <div class="tab-content">

      <%= flash_messages %>

      <div id="completed" class="tab-pane fade <%= active_tab(0) %>">
        <h3>Jobs</h3>
        <%#= render :partial => "jobs/multi_actions", :locals => { :can_only => [:run, :recheck, :delete_all, :download] } %>
        <div id="completed-p-jobs">
          <%= render :partial => "job/completed" %>
        </div>
      </div>
      <div id="new_job" class="tab-pane fade in <%= active_tab(1) %>">
        <div class="col-xs-12 col-sm-10 col-md-10 col-lg-10" style="float: none; margin: 0 auto;">
          <h3>KeywordSeparator - Add a NEW JOB</h3>
          <div id="new-job-form">
            <%= render :partial => "job/form" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>KeywordSeparator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>